backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "publications"
    label: "Publikationen"
    folder: "content/publications"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Autoren", name: "authors", widget: "string"}
      - {label: "Journal", name: "journal", widget: "string"}
      - {label: "Jahr", name: "year", widget: "number"}
      - {label: "Link / DOI", name: "link", widget: "string", required: false}
      - {label: "Kurzbeschreibung (optional)", name: "body", widget: "markdown", required: false}